- name: Example play
  hosts: ubuntu
  become: yes
  gather_facts: no
  serial: 1
  tasks:
    - name: Run apt-get update
      apt:
        update_cache: yes
        cache_valid_time: 1200

    - name: Install NGinx web server
      apt: name=nginx

    - name: Copy test page
      copy:
        src: test.html
        dest: /usr/share/nginx/html/test.html
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

- name: Fix hosts file for ubuntu1
  hosts: localhost
  tasks:
    - name: Add a hosts file entry
      become: yes
      lineinfile:
        dest: /etc/hosts
        line: 192.168.56.101 ubuntu1
        state: present